name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml
        coverage: none

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Verify bootstrap file
      run: test -f tests/bootstrap.php

    - name: Run PHPUnit tests
      run: ./vendor/bin/phpunit

    - name: Check code style
      run: ./vendor/bin/php-cs-fixer fix --dry-run --diff